version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - .\fluentd\conf:C:\fluent\conf
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: rajeshmuraleedharan/elasticsearch:nanoserver
    command: .\\bin\\elasticsearch.bat
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  kibana:
    image: sixeyed/kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

networks:
  default:
    driver: nat
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24