version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - .\fluentd\conf:C:\fluent\conf
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: rajeshmuraleedharan/elasticsearch:nanoserver
    command: .\\bin\\elasticsearch.bat
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  kibana:
    build: ./kibana
    # links:
    #   - "elasticsearch"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"

networks:
  default:
    driver: nat
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24  # Replace with a free subset of the prefix from the InternalIPInterfaceAddressPrefix field after running Get-NetNat PowerShell command (https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/advanced#windows-server-2016-work-arounds)