version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - .\fluentd\conf:C:\fluent\conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      default:
        ipv4_address: 172.19.1.24

  elasticsearch:
    build: ./elasticsearch
    # volumes:
      # - .\elasticsearch\config:C:\elasticsearch\config
      # - .\elasticsearch\data:C:\elasticsearch\data
      # - .\elasticsearch\logs:C:\elasticsearch\logs
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      default:
        ipv4_address: 172.19.1.92

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    networks:
      default:
        ipv4_address: 172.19.1.56

networks:
  default:
    name: efk_network
    driver: nat
    ipam:
      driver: default
      config:
      - subnet: 172.19.1.0/24  # Replace with a free subset of the prefix from the InternalIPInterfaceAddressPrefix field after running Get-NetNat PowerShell command (https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/advanced#windows-server-2016-work-arounds)